### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by abulazm22** [zerostaticthemes/jekyll-serif-theme#106]
I am trying to run theme with github pages but keep running into errors

```
> bundle exec jekyll serve
 Generating... 
      Remote Theme: Using theme zerostaticthemes/jekyll-serif-theme
       Jekyll Feed: Generating feed for posts
  Liquid Exception: Liquid error (/Users/mohamedabulazm/code/privat/welcome/_includes/main-menu-mobile.html line 2): Cannot sort a null object. included in /_layouts/default.html
jekyll 3.9.5 | Error:  Liquid error (/Users/mohamedabulazm/code/privat/welcome/_includes/main-menu-mobile.html line 2): Cannot sort a null object. included 
```

I tried the following config
```
remote_theme: "zerostaticthemes/jekyll-serif-theme"
plugins:
  - jekyll-environment-variables

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"

footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "Jekyll Serif Theme"
  meta_og_type: "website"
  meta_og_url: "https://jekyll-serif.netlify.app"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Jekyll Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_twitter_card: "summary"
  meta_twitter_site: "@zerostaticio"
  meta_twitter_creator: "@zerostaticio"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10
```
